sudo: false
language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install requests requests_toolbelt clint arrow
  - python setup.py install
script:
  - python setup.py test
matrix:
  allow_failures:
    - python: pypy
